---
- name: Get current Files Manager Enablement Status
  uri:
    url: "https://{{ role_nutanix_prism_api_url_base }}/api/nutanix/v3/services/nucalm/status"
    method: GET
    validate_certs: "{{ role_nutanix_pc_svc_files_mgr_host_validate_certs }}"
    body_format: json
    status_code: 200
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
  register: role_nutanix_pc_svc_files_mgr_state

- name: Debug role_nutanix_pc_svc_files_mgr_state
  debug:
    var: role_nutanix_pc_svc_files_mgr_state
  when:
    - role_nutanix_pc_svc_files_mgr_debug

- name: Current status of Files Manager service(s)
  debug:
    msg: "Files Manager is currently in a '{{ role_nutanix_pc_svc_files_mgr_state.json.service_enablement_status | lower }}' state."
